### ISSUE TITLE
Error building spec.emu

### ISSUE THREAD

**Issue by tom-sherman** [tc39/proposal-pattern-matching#165]
I'm trying to build the spec but getting a parser error from ecmarkup.

```
PS C:\Users\Tom\code\proposal-pattern-matching> npm run build

> proposal-pattern-matching@ build C:\Users\Tom\code\proposal-pattern-matching
> ecmarkup spec.emu index.html

Error: expecting ordered list, got whitespace
    at Parser.parseAlgorithm (C:\Users\Tom\code\proposal-pattern-matching\node_modules\ecmarkdown\dist\parser.js:41:19)
    at Function.parseAlgorithm (C:\Users\Tom\code\proposal-pattern-matching\node_modules\ecmarkdown\dist\parser.js:17:47)
    at Object.algorithm (C:\Users\Tom\code\proposal-pattern-matching\node_modules\ecmarkdown\dist\ecmarkdown.js:15:74)
    at Function.enter (C:\Users\Tom\code\proposal-pattern-matching\node_modules\ecmarkup\lib\Algorithm.js:14:19)
    at walk (C:\Users\Tom\code\proposal-pattern-matching\node_modules\ecmarkup\lib\Spec.js:712:17)
    at walk (C:\Users\Tom\code\proposal-pattern-matching\node_modules\ecmarkup\lib\Spec.js:716:13)
    at walk (C:\Users\Tom\code\proposal-pattern-matching\node_modules\ecmarkup\lib\Spec.js:716:13)
    at walk (C:\Users\Tom\code\proposal-pattern-matching\node_modules\ecmarkup\lib\Spec.js:716:13)
    at Spec.<anonymous> (C:\Users\Tom\code\proposal-pattern-matching\node_modules\ecmarkup\lib\Spec.js:169:13)
    at Generator.next (<anonymous>)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! proposal-pattern-matching@ build: `ecmarkup spec.emu index.html`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the proposal-pattern-matching@ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Tom\AppData\Roaming\npm-cache\_logs\2020-06-22T17_24_07_390Z-debug.log
```

**Comment by ljharb** [comment]
This repo's spec hasn't been updated in years, and the newer ecmarkup versions validate the spec more aggressively.

I wouldn't rely on the spec text currently included here, but I suspect if you downgrade ecmarkup sufficiently, it will build.

When this repo's spec is updated, this problem will resolve itself.
